### ISSUE TITLE
Lab1

### ISSUE THREAD

**Issue by AndreyIsakov01** [PavlovIO/Lab-work-1#1]
1) Загрузите исходное изображение для проверки, пожалуйста
2) Реализуйте функциональность в рамках класса

**Comment by AndreyIsakov01** [comment]
Не собирается
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/35789ea2-e7c2-4014-947f-962f9de6a483" />

**Comment by AndreyIsakov01** [comment]
<img width="407" alt="image" src="https://github.com/user-attachments/assets/91632b99-d25a-4887-9da0-423c75f3692c" />

**Comment by PavlovIO** [comment]
Issue fixed
